### ISSUE TITLE
[Task 4] Day of year problem

### ISSUE THREAD

**Issue by npaul19** [npaul19/hacktoberfest#113]
[Day of Year](https://github.com/npaul19/hacktoberfest/blob/main/Task-4/DayOfYear.java)

**Comment by hectorpasarin** [comment]
Hello. Would i work on this issue pls?

**Comment by hectorpasarin** [comment]
Please, check Pull Request  #116  
Thanks.

**Comment by npaul19** [comment]
Fixed
