### ISSUE TITLE
[Problem suggestion] Task 4

### ISSUE THREAD

**Issue by akbatra567** [npaul19/hacktoberfest#13]
## Write a function that will find the nth number in the Fibonacci Sequence

**Comment by VAIBHAV0526** [comment]
i will like to. work on this problem can you assign this to me? @akbatra567

**Comment by akbatra567** [comment]
Hey @VAIBHAV0526, I can't actually assign you. Probably @npaul19 can help you out ?

**Comment by npaul19** [comment]
Fixed by @VAIBHAV0526 in commit 427a8448f909b2a90e60a3f556f885106ef7a809
