### ISSUE TITLE
[Problem suggestion] Task 4: Longest Palindromic Substring Problem

### ISSUE THREAD

**Issue by akbatra567** [npaul19/hacktoberfest#15]
Write a program that finds the longest palindromic substring of a given string. Try to be as efficient as possible!

**Comment by Pavan49719** [comment]
Hey @akbatra567, Could I please work on this issue?

**Comment by akbatra567** [comment]
yes, it's open to suggestion. Go ahead and do it. @npaul19 could you please assign.

**Comment by npaul19** [comment]
Fixed in #24
