### ISSUE TITLE
[Task 4] Solve String Palindrome problem

### ISSUE THREAD

**Issue by npaul19** [npaul19/hacktoberfest#40]
Check whether the given input string is a palindrome or not
[String Palindrome](https://github.com/npaul19/hacktoberfest/blob/main/Task-4/StringPalindrome.java)

**Comment by s-aLman** [comment]
Hi @npaul19, I can do this. Could you please assign this one to me?

**Comment by Abhishek-Vaidya** [comment]
I can solve this problem optimally can you assign this issue to me?

**Comment by npaul19** [comment]
Both of you can solve this.
@s-aLman name your method as isPalindrome1()
@Abhishek-Vaidya name your method as isPalindrome2()
Add a comment for your time complexity even if it is same.
I'll merge both the codes.

**Comment by s-aLman** [comment]
@npaul19 Thanks for assigning. Just pushed my changes and created a PR. Please take a look 🙂.

**Comment by npaul19** [comment]
Fixed
