### ISSUE TITLE
[Task 5] Solve Diamond Pattern problem

### ISSUE THREAD

**Issue by npaul19** [npaul19/hacktoberfest#78]
Checkout README of [Task-5](/Task-5)
[Diamond Pattern](https://github.com/npaul19/hacktoberfest/blob/main/Task-5/DiamondPattern.cpp)

**Comment by Naisargika1402** [comment]
Can you assign me this?

**Comment by Naisargika1402** [comment]
Does the code need to be in Java only?

**Comment by npaul19** [comment]
No, what is your preferred language?
I can add a starter file in that language.

**Comment by Naisargika1402** [comment]
C++

**Comment by npaul19** [comment]
Okay, give me a minute.

**Comment by npaul19** [comment]
The problem has been updated.

**Comment by ahmd-nish** [comment]
@Naisargika1402  can i do this in python or Java ?

**Comment by npaul19** [comment]
Fixed
