### ISSUE TITLE
[Task 5] Solve Hollow Diamond Pattern problem

### ISSUE THREAD

**Issue by npaul19** [npaul19/hacktoberfest#95]
Checkout README of [Task-5](/Task-5)
[Hollow Diamond Pattern](https://github.com/npaul19/hacktoberfest/blob/main/Task-5/HollowDiamond.cpp)

**Comment by akhilender-bongirwar** [comment]
hi @npaul19 , can I do this ?

**Comment by kunalsingh1301** [comment]
hi @npaul19 , can i do this?

**Comment by npaul19** [comment]
I'll assign to the first person who comments.
@kunalsingh1301 I'll add more problems in some time. You can try those.

**Comment by akhilender-bongirwar** [comment]
hi @npaul19, can I do it in C++ ?

**Comment by npaul19** [comment]
Sure, I'll update the file from java to c++, give me a minute

**Comment by npaul19** [comment]
@akhilender-bongirwar  The file is updated.

**Comment by ahmd-nish** [comment]
Hi @npaul19  can I do this is python ?

**Comment by npaul19** [comment]
sure

**Comment by npaul19** [comment]
Fixed
