### ISSUE TITLE
[Task 5][Alphabets Pattern] Solve Diamond Pattern problem

### ISSUE THREAD

**Issue by npaul19** [npaul19/hacktoberfest#97]
Checkout README of [Task-5](/Task-5)
[Diamond Pattern](https://github.com/npaul19/hacktoberfest/blob/main/Task-5/AlphabetsPattern/DiamondPattern.java)

**Comment by mokshkori** [comment]
hey @npaul19 can you assign this to me?

**Comment by mokshkori** [comment]
Just Completed the task, it would be great if you review it.

**Comment by npaul19** [comment]
Fixed
