### ISSUE TITLE
[Task 5][Numbers Pattern] Solve Binary Pattern 1 problem

### ISSUE THREAD

**Issue by npaul19** [npaul19/hacktoberfest#98]
Checkout README of [Task-5](/Task-5)
[Binary Pattern 1](https://github.com/npaul19/hacktoberfest/blob/main/Task-5/NumbersPattern/BinaryPattern1.java)

**Comment by mokshkori** [comment]
Hey @npaul19 can you assign it to me.

**Comment by npaul19** [comment]
Fixed
